controllers:
    resource: ../../src/Controller/
    type: annotation

bundle-controller:
    resource: ../../src/Dervish/TestBundle/Controller/
    type: annotation



kernel:
    resource: ../../src/Kernel.php
    type: annotation
